In [4]:
import numpy as np
arr152 = np.array([20,30,40,50,60])
arr252 = np.array([20,90,40,50,70])
print(arr152)
print(arr252)
print(np.greater(arr152,arr252))
print(np.greater_equal(arr152,arr252))
print(np.less(arr152,arr252))
print(np.less_equal(arr152,arr252))

[20 30 40 50 60]
[20 90 40 50 70]
[False False False False False]
[ True False  True  True False]
[False  True False False  True]
[ True  True  True  True  True]


In [5]:
arr352=np.arange(30,71,2)
print("Array of all the even integers from 30 to 70")
print(arr352) 

Array of all the even integers from 30 to 70
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [6]:
arr452=np.identity(3)
print('3x3 matrix:')
print(arr452)

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [23]:
x52 = np.arange(21)
print("Original vector:")
print(x52)
print("After changing the sign of the numbers in the range from 9 to 15:")
x52[(x52 >= 9) & (x52 <= 15)] *= -1
print(x52)

Original vector:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
After changing the sign of the numbers in the range from 9 to 15:
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [8]:
x52 = np.diag([1, 2, 3, 4, 5])
print(x52)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [10]:
x52 = np.array([[5,8],[2,3]])
print("Original array:")
print(x52)
print("Sum of all elements:")
print(np.sum(x52))
print("Sum of each column:")
print(np.sum(x52, axis=0))
print("Sum of each row:")
print(np.sum(x52, axis=1))

Original array:
[[5 8]
 [2 3]]
Sum of all elements:
18
Sum of each column:
[ 7 11]
Sum of each row:
[13  5]


In [11]:
import os
x52 = np.arange(12).reshape(4, 3)
print("Original array:")
print(x52)
header = '0ne Two Three'
np.savetxt('temp.txt', x52, fmt="%d", header=header) 
print("After loading, content of the text file:")
result = np.loadtxt('temp.txt')
print(result)


Original array:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
After loading, content of the text file:
[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


In [20]:
num1 = np.array([0.5, 1.5, 0.23])
num2 = np.array([0.49, 1.5444444, 0.23])
print("\nOriginal arrays:")
np.set_printoptions(precision=10)
print(num1)
print(num2)
print("\n Two arrays are equal or not:?")
print(np.equal(num1, num2))


Original arrays:
[0.5  1.5  0.23]
[0.49      1.5444444 0.23     ]

 Two arrays are equal or not:?
[False False  True]


In [21]:
nums = np.arange(16, dtype='int').reshape(-1, 4)
print("Original array:")
print(nums)
print("\nswapping first and last rows of the said array:")
nums[[0,-1],:]=nums[[-1,0],:]
print(nums)

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

swapping first and last rows of the said array:
[[12 13 14 15]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 0  1  2  3]]


In [22]:
nums1 = np.array([[2, 5, 2],
              [1, 5, 5]])
nums2 = np.array([[5, 3, 4],
              [3, 2, 5]])
print("Array1:") 
print(nums1)
print("Array2:") 
print(nums2)
print("\nResult")
print(np.multiply(nums1, nums2))



Array1:
[[2 5 2]
 [1 5 5]]
Array2:
[[5 3 4]
 [3 2 5]]

Result
[[10 15  8]
 [ 3 10 25]]
