In [2]:
import numpy as np
rows=int(input("enter no. of rows"))
col=int(input("enetr no. of colums"))
print("enter matrix1 elements")
elements1= list(map(int, input().split()))
matrix1=np.array(elements1).reshape(rows,col)
print("enter matrix2 elements")
elements2=list(map(int, input().split()))
matrix2=np.array(elements2).reshape(rows,col)
print("matrix1 \n",matrix1)
print("matrix2 \n",matrix2)
print("dot product \n",np.dot(matrix1,matrix2))
print("transpose \n",np.transpose(matrix1))
print("trace \n",np.trace(matrix1))
print("rank \n",np.linalg.matrix_rank(matrix1))
print("determinant \n",np.linalg.det(matrix1))
print("inverse \n",np.linalg.inv(matrix1))
w, v = np.linalg.eig(matrix1)
print("\nEigenvalues:")
print(w)
print("\nEigenvectors:")
print(v)

enter no. of rows 2
enetr no. of colums 2


enter matrix1 elements


 12 13 14 15


enter matrix2 elements


 17 16 18 19


matrix1 
 [[12 13]
 [14 15]]
matrix2 
 [[17 16]
 [18 19]]
dot product 
 [[438 439]
 [508 509]]
transpose 
 [[12 14]
 [13 15]]
trace 
 27
rank 
 2
determinant 
 -2.0000000000000173
inverse 
 [[-7.5  6.5]
 [ 7.  -6. ]]

Eigenvalues:
[-0.07387196 27.07387196]

Eigenvectors:
[[-0.73272482 -0.65309186]
 [ 0.68052505 -0.7572787 ]]
